name: Hello World

on:
  push:

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo "Hello GitHub Action!"
  second-job:
    runs-on: windows-latest
    steps:
      - run: echo "this jo is running on ${{ runner.os }}"
